In [1]:
%run Standard_functions.ipynb

In [23]:
%run Encoder_decoder.ipynb

353828
['product', 'made', 'with', 'more', 'than', '50', 'percent', 'recycled', 'material', ',', 'and', 'we’re', 'making', 'important', 'strides', 'across', 'all', 'of', 'our', 'products', '.', 'The', 'iPhone', '15', 'lineup', ',', 'Apple', 'Watch', 'Series', '9', ',', 'and', 'Apple', 'Watch', 'Ultra', '2', 'use', '100', 'percent', 'recycled', 'cobalt', 'in', 'their', 'batteries', '.']
['sourcing', 'and', 'utilizing', 'materials', ',', 'relying', 'on', 'recycled', 'and', 'renewable', 'materials', 'for', 'our', 'products', 'and', 'packaging', ',', 'and', 'reducing', 'scrap', '.', 'And', 'we', 'also', 'maintain', 'strict', 'standards', 'for', 'responsibly', 'sourcing']
59452
6163
{'\x07': 0, '\x07\x07Splash': 1, '\x07Aerospace-grade': 2, '\x07Apple': 3, '\x07Bottom': 4, '\x07Emissions': 5, '\x07Features': 6, '\x07Projected': 7, '\x07Rear': 8, '\x07Repairable': 9, '\x07Sapphire': 10, '\x07Splash': 11, '\x07Surgical-grade': 12, '\x08': 13, '$200': 14, '$280': 15, '$280M': 16, '$30': 17, '$

Note: you may need to restart the kernel to use updated packages.
tiktoken version: 0.9.0
Appendix <|endoftext|> How can we advance sustainability? 2024 Environmental Sustainability Repo
[4677, 19573, 220, 50256, 1374, 460, 356, 5963, 26809, 30, 48609, 13272, 311, 19542, 1799, 1432, 78]
Appendix <|endoftext|> How can we advance sustainability? 2024 Environmental Sustainability Repo
[35, 571, 88, 19173, 13881]
Dibyaranjan


In [2]:
import importlib
import tiktoken

print("tiktoken version:", importlib.metadata.version("tiktoken"))

tiktoken version: 0.9.0


In [3]:
tokenizer = tiktoken.get_encoding('gpt2')

# Understanding Input Output pairs with a sample

In [4]:
final_text_input_encoder = tokenizer.encode(text,allowed_special={'<|endoftext|>'})

print(final_text_input_encoder)

[47213, 18387, 6358, 17546, 278, 9068, 614, 1160, 1954, 26714, 13272, 16204, 2929, 4196, 25054, 1367, 15120, 284, 4196, 25054, 1105, 38066, 1315, 8495, 290, 5696, 1987, 42048, 3933, 4128, 8971, 3439, 23699, 9934, 13864, 5014, 38066, 2319, 8721, 28188, 4153, 14633, 7628, 4764, 5638, 6740, 12169, 7030, 2439, 2571, 27867, 7618, 38066, 7863, 337, 5912, 8454, 25809, 8093, 27724, 22395, 513, 6524, 26448, 422, 15378, 6612, 604, 6358, 11330, 642, 28510, 290, 4371, 1985, 5082, 290, 37866, 1590, 8275, 38066, 8257, 7343, 3101, 284, 257, 2837, 286, 10839, 8644, 317, 3043, 1075, 1487, 1978, 8854, 44188, 5348, 8688, 6060, 8541, 3469, 4803, 3623, 8971, 8699, 3334, 3081, 6588, 20835, 9225, 23699, 24713, 416, 1720, 9773, 6682, 9415, 13864, 9698, 14435, 2890, 5087, 30378, 7600, 317, 25, 26040, 7291, 2568, 10327, 10048, 347, 25, 4196, 447, 247, 82, 1204, 6772, 8922, 20411, 9907, 327, 25, 2195, 3874, 290, 2423, 6299, 16226, 360, 25, 9344, 11, 3893, 290, 11233, 7820, 16003, 412, 25, 19694, 1478, 8298, 1809

In [5]:
encode_sample = final_text_input_encoder[:80] #taking a sample to understand
print(encode_sample)

[47213, 18387, 6358, 17546, 278, 9068, 614, 1160, 1954, 26714, 13272, 16204, 2929, 4196, 25054, 1367, 15120, 284, 4196, 25054, 1105, 38066, 1315, 8495, 290, 5696, 1987, 42048, 3933, 4128, 8971, 3439, 23699, 9934, 13864, 5014, 38066, 2319, 8721, 28188, 4153, 14633, 7628, 4764, 5638, 6740, 12169, 7030, 2439, 2571, 27867, 7618, 38066, 7863, 337, 5912, 8454, 25809, 8093, 27724, 22395, 513, 6524, 26448, 422, 15378, 6612, 604, 6358, 11330, 642, 28510, 290, 4371, 1985, 5082, 290, 37866, 1590, 8275]


In [6]:
context_size = 8 #creating context input length

#The context size of 8 means the model is trained to look into a sequence of 8 words (or tokens)
#Inorder to predict the next word in the sequence
#The input x is the first 8 tokens [1,2,3,4,5,6,7,8], and the target y is the next 8 tokens [2,3,4,5,6,7,8,9]

x = encode_sample[:context_size]
y = encode_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:         {y}")

x: [47213, 18387, 6358, 17546, 278, 9068, 614, 1160]
y:         [18387, 6358, 17546, 278, 9068, 614, 1160, 1954]


In [7]:
for i in range(1,context_size+1):
    context = encode_sample[:i]
    desired = encode_sample[i]
    #print(desired)
    #print(context, "---->", desired)
    print(tokenizer.decode(context), "----->", tokenizer.decode([desired]))

Environmental ----->  Progress
Environmental Progress ----->  Report
Environmental Progress Report ----->  Cover
Environmental Progress Report Cover -----> ing
Environmental Progress Report Covering ----->  fiscal
Environmental Progress Report Covering fiscal ----->  year
Environmental Progress Report Covering fiscal year ----->  20
Environmental Progress Report Covering fiscal year 20 -----> 23


# Implementation of Data Loader

In [8]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [9]:
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):  #max_length is context_size and stride is how much slide to be done
        self.input_ids = []
        self.target_ids = []
        
        #tokenzation of entire text
        token_ids = tokenizer.encode(txt,allowed_special={'<|endoftext|>'})
        
        for i in range(0,len(token_ids)-max_length,stride):
            input_chunck = token_ids[i:i + max_length]
            target_chunck = token_ids[i+1:i + max_length+1]
            self.input_ids.append(torch.tensor(input_chunck))
            self.target_ids.append(torch.tensor(target_chunck))
    
    def __len__(self):
        return len(self.input_ids)
    
    
    def __getitem__(self,idx):
        return self.input_ids[idx], self.target_ids[idx]
            

In [10]:
import tiktoken

def create_dataloader_v1(txt,batch_size=8, max_length=256, 
                      stride=128, shuffle=True, 
                      drop_last=True,num_workers=0):  #batch_size is the number of batches the model processes at once before updating its parameter
                                                    # max_length is the context window, gpt can handle 256 context window
                                                    # stride is at a time how much shift you want to do
                                                    # shuffle is randomly shuffle data before batching the data if it is set to true
                                                    # drop_last is used to control whether you want to drop the incomplete batch while batching the dataset
                                                    # num_worker controls the number of parallel worker process used for data loading
    #Initialization of tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")
    
    #Creation of dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
    
    #create Dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )
    return dataloader

# Sample example to understand above

In [12]:
import torch
dataloader = create_dataloader_v1(text, batch_size=1, max_length=4, stride=3, shuffle=False)

data_iter = iter(dataloader)
first_batch = next(data_iter)
second_batch = next(data_iter)
print(first_batch),print(second_batch)

[tensor([[47213, 18387,  6358, 17546]]), tensor([[18387,  6358, 17546,   278]])]
[tensor([[17546,   278,  9068,   614]]), tensor([[ 278, 9068,  614, 1160]])]


(None, None)

In [13]:
dataloader = create_dataloader_v1(text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("inputs:",inputs)
print("targets:", targets)

inputs: tensor([[47213, 18387,  6358, 17546],
        [  278,  9068,   614,  1160],
        [ 1954, 26714, 13272, 16204],
        [ 2929,  4196, 25054,  1367],
        [15120,   284,  4196, 25054],
        [ 1105, 38066,  1315,  8495],
        [  290,  5696,  1987, 42048],
        [ 3933,  4128,  8971,  3439]])
targets: tensor([[18387,  6358, 17546,   278],
        [ 9068,   614,  1160,  1954],
        [26714, 13272, 16204,  2929],
        [ 4196, 25054,  1367, 15120],
        [  284,  4196, 25054,  1105],
        [38066,  1315,  8495,   290],
        [ 5696,  1987, 42048,  3933],
        [ 4128,  8971,  3439, 23699]])


# Creating Token Embeddings

In [15]:
input_ids = torch.tensor([2,3,5,1])
print(input_ids)

tensor([2, 3, 5, 1])


In [17]:
vocab_size = 6
out_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size,out_dim)

print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [19]:
print(embedding_layer(torch.tensor([2])))

tensor([[ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)


In [20]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


# Positional Embedding (Encoding word positions)

In [22]:
vocab_size = 50257
out_dim = 768

token_embedding_layer = torch.nn.Embedding(vocab_size,out_dim)

print(token_embedding_layer.weight)

Parameter containing:
tensor([[-0.0171, -1.0054,  0.9135,  ..., -1.6518, -0.6185,  1.6938],
        [-0.5526,  1.6596, -0.0655,  ...,  0.5268, -1.3640, -1.2460],
        [ 0.8122,  1.2448, -1.2796,  ...,  1.0586, -0.3220, -1.2585],
        ...,
        [-0.3299, -0.4851,  1.2602,  ..., -2.3041, -0.0910, -0.1348],
        [ 0.3748,  0.0830, -0.0102,  ..., -1.3540,  0.2102,  0.0852],
        [ 1.1640,  0.1949,  0.0794,  ..., -0.6998,  0.8277, -0.0674]],
       requires_grad=True)


In [29]:
max_length = 4

dataloader = create_dataloader_v1(text,batch_size=8,max_length=max_length,stride=max_length,shuffle=False)
data = iter(dataloader)
inputs, targets = next(data)

In [32]:
print(inputs), print(targets), print(inputs.shape), print(targets.shape)

tensor([[47213, 18387,  6358, 17546],
        [  278,  9068,   614,  1160],
        [ 1954, 26714, 13272, 16204],
        [ 2929,  4196, 25054,  1367],
        [15120,   284,  4196, 25054],
        [ 1105, 38066,  1315,  8495],
        [  290,  5696,  1987, 42048],
        [ 3933,  4128,  8971,  3439]])
tensor([[18387,  6358, 17546,   278],
        [ 9068,   614,  1160,  1954],
        [26714, 13272, 16204,  2929],
        [ 4196, 25054,  1367, 15120],
        [  284,  4196, 25054,  1105],
        [38066,  1315,  8495,   290],
        [ 5696,  1987, 42048,  3933],
        [ 4128,  8971,  3439, 23699]])
torch.Size([8, 4])
torch.Size([8, 4])


(None, None, None, None)

In [36]:
token_embedding = token_embedding_layer(inputs)
print(token_embedding), print(token_embedding.shape)

tensor([[[ 1.1763,  0.0813, -0.5542,  ..., -0.1995, -0.7508,  0.5909],
         [ 1.6127,  0.3443,  0.4126,  ..., -1.4215, -0.0920,  0.3532],
         [-1.6565,  0.3330,  0.9812,  ..., -0.2423,  0.0383,  0.7535],
         [ 0.3989, -1.5300, -0.4613,  ..., -1.0145, -0.4721, -0.6393]],

        [[-0.2300,  0.8624, -0.5803,  ...,  0.2785,  0.9857,  1.0635],
         [ 0.1448, -0.8308, -1.4764,  ...,  2.0961, -0.7177,  0.4185],
         [-0.7887,  0.8080,  0.0685,  ...,  1.1017,  1.1879,  1.2563],
         [ 1.6233, -0.2470, -0.5404,  ...,  0.1496,  0.2242, -0.8465]],

        [[-1.4150, -0.9603, -0.3291,  ..., -1.1092, -0.0999, -1.0279],
         [-0.6069, -1.3358,  0.3310,  ...,  1.2030, -0.1933,  1.4440],
         [-0.0956,  0.9074, -0.2105,  ...,  0.9578, -1.0864,  1.3479],
         [ 0.9008,  0.5464, -0.0859,  ...,  0.4239, -2.6805,  1.3499]],

        ...,

        [[-0.2841,  0.1528, -0.0046,  ...,  1.3775, -0.1686, -0.2018],
         [-0.8549,  0.6845,  1.7826,  ...,  0.0566, -0.51

(None, None)

In [40]:
context_length = max_length

positional_embedding_layer = torch.nn.Embedding(context_length,out_dim)

pos_embedding = positional_embedding_layer(torch.arange(max_length))

print(positional_embedding_layer.weight), print(pos_embedding.shape)

Parameter containing:
tensor([[ 0.4716,  0.1211,  0.4962,  ..., -0.1514,  0.3078, -0.9861],
        [-0.5131, -0.5683, -0.5749,  ..., -1.2800,  0.7319,  2.4215],
        [ 1.1673,  0.0282,  0.1255,  ...,  2.2058, -1.5358, -0.6095],
        [-0.1713, -0.0271, -0.3492,  ..., -0.4890, -0.3086, -2.6654]],
       requires_grad=True)
torch.Size([4, 768])


(None, None)

In [44]:
final_input_embedding = token_embedding + pos_embedding

print(final_input_embedding), print(final_input_embedding.shape)

tensor([[[ 1.6480,  0.2024, -0.0580,  ..., -0.3509, -0.4430, -0.3952],
         [ 1.0995, -0.2241, -0.1623,  ..., -2.7015,  0.6399,  2.7747],
         [-0.4893,  0.3612,  1.1067,  ...,  1.9635, -1.4976,  0.1440],
         [ 0.2276, -1.5572, -0.8106,  ..., -1.5035, -0.7807, -3.3047]],

        [[ 0.2417,  0.9835, -0.0841,  ...,  0.1270,  1.2935,  0.0775],
         [-0.3683, -1.3991, -2.0513,  ...,  0.8160,  0.0142,  2.8400],
         [ 0.3785,  0.8362,  0.1940,  ...,  3.3075, -0.3479,  0.6468],
         [ 1.4520, -0.2741, -0.8896,  ..., -0.3393, -0.0844, -3.5119]],

        [[-0.9433, -0.8392,  0.1672,  ..., -1.2606,  0.2079, -2.0140],
         [-1.1200, -1.9042, -0.2439,  ..., -0.0771,  0.5386,  3.8655],
         [ 1.0717,  0.9355, -0.0851,  ...,  3.1636, -2.6223,  0.7384],
         [ 0.7295,  0.5192, -0.4352,  ..., -0.0651, -2.9891, -1.3155]],

        ...,

        [[ 0.1876,  0.2739,  0.4916,  ...,  1.2261,  0.1392, -1.1878],
         [-1.3681,  0.1162,  1.2077,  ..., -1.2234,  0.21

(None, None)